# rgaParkour v1.0.0 Configuration
parkour-kit:
  checkpoint-materials:
    - "LIGHT_WEIGHTED_PRESSURE_PLATE"
    - "GOLD_PRESSURE_PLATE"
  finish-materials:
    - "HEAVY_WEIGHTED_PRESSURE_PLATE"
    - "IRON_PRESSURE_PLATE"
  fail-materials:
    - "LAVA"
    - "WATER"
game:
  fall-threshold-y: -60
  max-match-duration-seconds: 300
  invulnerability-seconds-on-fail: 1
